variables:
  CI_DOCKERHUB_IMAGE: huncrys/plexsso

include:
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/docker-publish@~latest
    inputs:
      architectures:
        - amd64
        - arm64
        - arm/v7
